server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # 静态资源缓存（CSS/JS/图片/字体）
    location ~* \.(css|js|svg|ico|woff2?|png|jpg|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # 启用在 Astro 生成的 404.html
    error_page 404 /404.html;

    # Gzip 压缩（提升传输速度）
    gzip on;
    gzip_types text/html text/css application/javascript image/svg+xml;
    gzip_min_length 1024;
}
